services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.fxsim.rule=Host(`fxsim.gberti.com`)'
      - 'traefik.http.routers.fxsim.entrypoints=websecure'
      - 'traefik.http.routers.fxsim.tls=true'
      - 'traefik.http.routers.fxsim.tls.certresolver=leresolver'
      - 'traefik.http.services.fxsim.loadbalancer.server.port=80'
    environment:
      - NODE_ENV=production
    networks:
      - traefik

networks:
  traefik:
    external: true
